 <?
    $groups     = $this->url (array ('action'=>'groups') );
    $bookmarks  = $this->url (array ('controller'=>'bookmarks', 'action'=>'index') );
    $next       = $this->url (array ('controller'=>'article', 'action'=>'index', 'on' => 1) ); 
 ?>


<input type="hidden" id="text-user" value="<?= $this->User ?>"/>
<input type="hidden" id="text-page" value="<?= $next ?>"/>


           <div class="header">Loading...</div>  
 
<table width="100%">
  <tr>
    <td align="center">
	Subscribed Groups | <a href="<?= $bookmarks ?>">Bookmarks</a> | <a href="<?= $groups ?>">All Groups</a>
    </td>
  </tr>
  <tr>
    <td>
        <ul>
 
	   <? foreach ($this->Groups as $group): ?>

	<li class="group-name carousel" id="<?= $group -> Name ?>">
	   <a class="list-item">
	    <span class="link" id="/index/"><?= $group -> Name ?></span>
	    <span class="column1"><?= $group -> Count ?><span>
	    <span class="column2"><?= $group -> Tally ?><span>
	   </a>
	</li>

	   <? endforeach ?>

        </ul>
    </td>
  </tr>
</table>
 
