 <?
  $action = $this -> saved ? "Unsubscribe from {$this->group->Name}" : "Subscribe to {$this->group->Name}";
  $amount = 50000;
  $lowid  = $this->group->LowID - $amount;

  if ($lowid < $this->group->MinID)
  {
      $lowid = $this->group->MinID;
      $amount = $this->group->LowID - $lowid;
  }
  $data = array (
           
    $this->group->LowID,
    $this->group->HighID, 
    $this->group->MinID,
    $this->group->MaxID  

     );


?> 

  <ul class="my-menu">


    <li><a class="bookmark" id="/rpc/subscribe/id/<?= $this->group->Key ?>/user/<?= $this->user ?>"><?= $action ?></a></li>

<? if ($amount > 0): ?>
    <li><a class="group-join <?= $this->group->LowID ?> <?= $amount ?>" id="<?= $this->group->Name ?>">Get the previous <?= $amount ?> items starting at <?= $this->group->LowID ?>...</a></li> 
<? endif ?>

    <li><a class="group-renew" id="<?= $this->group->Name ?>">Clear all articles and reload...</a></li> 


    <li><a>Show only items with at least</a>

      <ul>

<? for ($x=0;$x<250;$x+=25): ?>
     <li 
             <?if ($x==$this->most): ?>
                 class="selected" 
             <? endif ?>
         ><a class="a-count" id="<?= $x ?>"><?= $x ?> items</a>

         </li>
<? endfor?> 

      </ul>
 
      </li> 




    <li>
 <a>Open related group </a>
      <ul>
<? while (list($name,$val) = each ($this->refs) ): ?>

       <?if (strlen($name) > 10): ?>
      <li 
         ><a id="<?= $name ?>" class="a-group"><?= $name ?></a></li>
        <?endif?>

<? endwhile ?>
      </ul>

      </li> 


<? if (sizeof($this->searches) > 0): ?> 
    <li>
        <a>Saved searches</a>

      <ul>

<? foreach ($this->searches as $search): ?>
     <li 
             <?if ($search==$this->search): ?>
                 class="selected" 
             <? endif ?>
         ><a href='<?= $this->url(array("search" => $search, "page" => 1, "most" => NULL)) ?>'><?= $search ?></a>

         </li>
<? endforeach?> 

      </ul>
 

     
   </li>

<? endif ?>

</ul>
 
   <input type="hidden" id="text-user" value="<?= $this->user ?>"/>   
 
  
 
                    <div id="div-stat"><?= $this -> pages ?></div>

                    <ul class="rounded">

		 <? foreach ($this->articles as $article):
                            $css    = $article -> cache ? "cache" : "";
                            $bk     = $article -> bookmarked ? "** " : "";
                            $count  = $article -> count;

                       $parts  = sizeof ( explode("-", $article -> id) );
                       if (preg_match('/\((\d+)\/(\d+)\)/', $article -> subject, $x))
                       {
                           $countof = $x[2];
                           $hue = $countof == $parts ? "#000" : "#900";
                       }

                            ?>
		     
			<li style="color:<?= $hue ?>" class="<?= $count ?> arrow article-<?= $article -> type ?> <?= $css?>" id="<?= $article -> uuid ?>" 
			    ><?= $article->date ?>, <?= $article -> subject ?><?= $parts ?>, <?= $countof ?></li> 
			
		   
		<? endforeach ?>

                    </ul> 
  
 
<div id="dialog" title="<?= $this->group->Name ?> options">

    <li> <div class="span-of" id="<?= implode ('x', $data) ?>">loading...</div></li> 


</div> 

