<?

?>

<div class="controller">

    <div>
   
	<div class="article-menu"><span class="ui-icon ui-icon-circle-triangle-s"></span></div>  

    <select id="article-select">
        <? foreach ($this-> items as $article): 
           $value = $this->unrar == "" ? trunc($article -> subject, 50) : $article -> filename ;
           $value = str_replace ('"', '', $value ); 
           $value = str_replace ('<', '&lt;', $value );
           $value = str_replace ('>', '&gt;', $value );?> 
         <option value="<?= $article -> uuid ?>"
            <? if ($article -> uuid == $this -> uuid ): ?>
                selected 
            <? endif ?>
           >
           <?= $value ?>
         </option>
        <? endforeach ?> 
    </select>

   </div>
 <canvas id="canvas-teeny" width="724" height="124"></canvas> 

</div>

<ul class="article-lookup">

        <? foreach ($this-> items as $article): ?> 
         <li data-article-index="<?= $article -> uuid ?>" 
           ><?= $article -> subject ?></li>
        <? endforeach ?> 

</ul>
