
   <input type="hidden" id="text-user" value="<?= $this->user ?>"/>   
 
  <ul class="my-menu">
<li>
<a id="<?= $this->group ?>" class="a-group">Open <?= $this->group ?></a></li>
</ul> 

                 <div id="div-stat"><?= $this -> pages ?></div> 

                   <ul class="rounded">

		 <? foreach ($this->User->Bookmarks as $article):  ?>
		     
			<li class="<?= $article->count ?> arrow article-picture" id="<?= $article -> uuid ?>"
                           data-article-key="<?= $article -> uuid  ?>"><?= $article -> subject  ?>)</li>
		   
		 <? endforeach ?>

                    </ul>    
