 <?
    $action = $this->article->bookmarked ? "Unbookmark" : "Bookmark";  
    $sortas  = strlen($this->sort) > 0 ? "subject" : "filename";  
 
?>

  <ul class="my-menu"> 
    <li class="li-sortas"><a>Sort by <?= $sortas ?></a></li> 
    <li><a class="bookmark" id="/rpc/bookmark/id/<?= $this->article -> uuid ?>/user/<?= $this->article->username ?>"><?= $action ?></a></li>
 
</ul> 

   <input type="hidden" id="text-suffix" value="name/<?= $this->article->groupname ?>/user/<?= $this->article->username ?>"/>


    <div class="a-next 1 article-scale" id="<?= $this -> id ?>" title="name/<?= $this->article->groupname ?>/user/<?= $this->article->username ?>"
     ><?= $this -> chosen -> subject ?></div>

 
   <?php echo $this->partial('controller.phtml', 
       array ( 
               items => $this->article->items
             , uuid => $this->  id
             , unrar => ""
   ) ); ?>



