<?
$css = isset ($this->css) ? $this->css : "scroll";
?>

<html>
	<title><?= $this -> title ?></title> 

<meta id="meta-v" name="viewport" content="width=device-width, user-scalable=no, minimal-ui, initial-scale=1.0">


	<link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" href="//code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css"> 
	<link rel="stylesheet" href="/style/style-new.css"> 

	<script data-main="/scripts/app/main" src="/scripts/app/require.js"></script>
  
	<body>
	  


            <div id="ajax" class="current">


                <div id="header" class="toolbar">

                    <h1> <a><?= trunc($this -> title) ?></a> </h1>

                    <? if (isset($this->back)):?>
                    <div class="leftButton" id="<?= $this -> back ?>">Back</div> 
                    <? endif ?>

                    <? if (isset($this->option)):?>
                    <div class="rightButton"><?= $this->option ?></div>
                    <? endif ?>

                </div>


                <div class="<?= $css ?>"> 

                    <? if (isset($this->nav)): ?>
                    
                       <div class="navigator">

                      <? foreach ($this->nav as $nav): ?> 

                        <? if ($nav->Href) :?> 
                             <a class="link" id="<?= $nav->Href ?>"><?= trunc($nav->Text, 30) ?></a> &#160;&#187;&#160;
                        <? else: ?>
                             <span class="dyn-caption"><?= trunc($nav->Text,75) ?></span>
                        <? endif ?>          

                      <? endforeach ?>
     
                           <div class="settings-button"></div>

                       </div>          
                    <? endif ?>

                    <?php echo $this->layout()->content; ?>

                </div>

            </div>


           <? if (isset($this->next)):?>
           <input type="hidden" id="text-page" value="<?= $this-> next ?>"/>
           <? endif ?>


      </body>
	  
	<script src="//code.jquery.com/jquery-1.9.1.js"></script>
	<script src="//code.jquery.com/ui/1.10.4/jquery-ui.js"></script>  
</html>
