<html>
	<title>ec2-54-85-50-17.compute-1.amazonaws.com</title> 
<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0">
	 <link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
     <link rel="stylesheet" href="//code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css">
     <link rel="stylesheet" href="/style/style.css">
     <script src="//code.jquery.com/jquery-1.9.1.js"></script>
     <script src="//code.jquery.com/ui/1.10.4/jquery-ui.js"></script> 
	<script src="/scripts/controller.js"></script>
	<script src="/scripts/bus.js"></script>
	<script src="/scripts/canvasapi.js"></script>
	<script src="/scripts/image.js"></script>
	<script src="/scripts/frame.js"></script>
	 
	<body>
	  
               <?php echo $this->layout()->content; ?>

      </body>
</html>
