<html>
	<title>ec2-54-85-50-17.compute-1.amazonaws.com</title> 
<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0">
	 <link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
     <link rel="stylesheet" href="//code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css">
     <link rel="stylesheet" href="/style/style.css">
     <script src="//code.jquery.com/jquery-1.9.1.js"></script>
     <script src="//code.jquery.com/ui/1.10.4/jquery-ui.js"></script> 
	 
	<script src="/scripts/require.js"></script>
	<script src="/scripts/controller.js"></script>
	<script src="/scripts/bus.js"></script>
	<script src="/scripts/canvasapi.js"></script>
	<script src="/scripts/image.js"></script>
	<script src="/scripts/frame.js"></script>
<!--	<script src="/scripts/batchpane.js"></script> -->
	<script src="/scripts/worker.js"></script>
	 
	<body>
	  
               <?php echo $this->layout()->content; ?>

      </body>
	  <script language="javascript">

	  requirejs.config({
			//By default load any module IDs from scripts/worker
			baseUrl: '/scripts/worker', 
			//except, if the module ID starts with "app",
			//load it from the js/app directory. paths
			//config is relative to the baseUrl, and
			//never includes a ".js" extension since
			//the paths config could be for a directory.
			paths: {
				app: '../app'
			}
		});

	</script>
</html>
